### ISSUE TITLE
Failed to invoke clarifai2.dto.ClarifaiStatus() with no args

### ISSUE THREAD

**Issue by hackable** [Clarifai/clarifai-java#26]
Any help would be appreciated

Source Code:

``` java
package com.proptiger.data.service.cms.listing;


import java.util.List;

import clarifai2.api.ClarifaiBuilder;
import clarifai2.api.ClarifaiClient;
import clarifai2.api.ClarifaiToken;
import clarifai2.api.request.ClarifaiRequest;
import clarifai2.dto.input.ClarifaiInput;
import clarifai2.dto.input.image.ClarifaiImage;
import clarifai2.dto.model.output.ClarifaiOutput;
import clarifai2.dto.prediction.Prediction;
public class ListingAutoApprovalService {
    private void clarifyresponse(String URL) {
        final ClarifaiClient client = new ClarifaiBuilder(
                "{{app_id}}",
                "{{app_secret}}").buildSync();
        ClarifaiToken token = client.getToken();

        @SuppressWarnings("unused")
        final ClarifaiRequest<List<ClarifaiOutput<Prediction>>> predictionResults =
                client.predict("{{model_id}}")
                        .withInputs(ClarifaiInput.forImage(ClarifaiImage.of(URL))).build();
        @SuppressWarnings("unused")
        ClarifaiToken token1 = client.getToken();
        // predictionResults.getStatus();
        /*
         * final ClarifaiResponse<List<ClarifaiOutput<Concept>>>
         * predictionResults = client.getDefaultModels().generalModel() // You
         * can also do client.getModelByID("id") to get custom models .predict()
         * .withInputs( ClarifaiInput.forImage(ClarifaiImage.of(
         * "https://samples.clarifai.com/metro-north.jpg")) ) .executeSync() ;
         * /*
         * 
         * // String token = "fvFlUXSr7Z2d1BwJ3QzFZDoMoKhg4o"; /* ClarifaiClient
         * client = new ClarifaiBuilder(
         * "{{app_id}}",
         *"{{app_secret}}").buildSync();
         */
       // client.predict("f5385c66fe154fb9b3271ad3b5d2bb4a").withInputs(ClarifaiInput.forImage(ClarifaiImage.of(URL)))
         //       .executeSync();

    }

    public static void main(String args[]) {
        ListingAutoApprovalService object = new ListingAutoApprovalService();

        System.out.print("test");
        object.clarifyresponse("https://content.makaan.com/16/7268897/274/6562459.jpeg");
        System.out.print("test");
    }

}


```

`
Exception in thread "main" java.lang.RuntimeException: Failed to invoke clarifai2.dto.ClarifaiStatus() with no args
    at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:107)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162)
    at com.google.gson.Gson.fromJson(Gson.java:803)
    at com.google.gson.Gson.fromJson(Gson.java:868)
    at com.google.gson.Gson.fromJson(Gson.java:841)
    at clarifai2.api.request.ClarifaiRequestImpl.getClarifaiResponse(ClarifaiRequestImpl.java:78)
    at clarifai2.api.request.ClarifaiRequestImpl.executeSync(ClarifaiRequestImpl.java:43)
    at clarifai2.api.request.ClarifaiRequest$Builder.executeSync(ClarifaiRequest.java:188)
    at com.proptiger.data.service.cms.listing.ListingAutoApprovalService.clarifyresponse(ListingAutoApprovalService.java:21)
    at com.proptiger.data.service.cms.listing.ListingAutoApprovalService.main(ListingAutoApprovalService.java:36)
Caused by: java.lang.InstantiationException
    at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:104)
    ... 9 more
`

**Comment by kevinmost** [comment]
Hi @hackable, thank you for the bug report. I'm trying to reproduce this and might need a bit more info.

Are you using the latest version (currently 2.0.2) of the API client?

Did you get this exception with the code exactly as-is, including that section being commented out? I ask because the code that you provided is not calling `.executeSync()` anywhere (and we shouldn't be using that method internally anywhere in the client).

The problem seems to be that our `Gson` instance is not aware of the custom deserializer that it should be using, which is unusual.

**Comment by hackable** [comment]
We are using version 2.0.2  and JSON returned is probably this.

{"status":{"code":99009,"description":"Internal error","details":"runtime error: invalid memory address or nil pointer dereference"}}



```java
import clarifai2.api.ClarifaiBuilder;
import clarifai2.api.ClarifaiClient;
import clarifai2.api.request.ClarifaiPaginatedRequest;
import clarifai2.api.request.ClarifaiPaginatedRequest.Builder;
import clarifai2.api.request.model.PredictRequest;
import clarifai2.dto.input.ClarifaiInput;
import clarifai2.dto.input.image.ClarifaiImage;
import clarifai2.dto.model.Model;
import clarifai2.dto.prediction.Prediction;
public class ListingAutoLiveClarifai {
    private void clarifyresponse(String URL) {
        final ClarifaiClient client = new ClarifaiBuilder(
                "{app-id}",
                "{app-key}").buildSync();
        Builder<List<Model<?>>, ?> builder = client.getModels();
        ClarifaiPaginatedRequest request = builder.build();

        PredictRequest<Prediction> prediction = client.predict("{model-id}")
                .withInputs(ClarifaiInput.forImage(ClarifaiImage.of(URL)));
        prediction.executeSync();
    }
    public static void main(String args[]) {
        ListingAutoLiveClarifai object = new ListingAutoLiveClarifai();

        System.out.print("test");
        object.clarifyresponse("img_url");
        System.out.print("test");
    }

}
Exception in thread "main" java.lang.RuntimeException: Failed to invoke clarifai2.dto.ClarifaiStatus() with no args
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:107)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:868)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at clarifai2.api.request.ClarifaiRequestImpl.getClarifaiResponse(ClarifaiRequestImpl.java:78)
	at clarifai2.api.request.ClarifaiRequestImpl.executeSync(ClarifaiRequestImpl.java:43)
	at clarifai2.api.request.ClarifaiRequest$Builder.executeSync(ClarifaiRequest.java:188)
	at com.proptiger.pixie.service.ListingAutoLiveClarifai.clarifyresponse(ListingAutoLiveClarifai.java:47)
	at com.proptiger.pixie.service.ListingAutoLiveClarifai.main(ListingAutoLiveClarifai.java:65)
Caused by: java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:104)
	... 9 more
```

**Comment by kevinmost** [comment]
@hackable: Hmm, I'm having trouble reproducing this error. Is it consistently happening every time that you run the snippet above, or is it sporadic?

The JSON you shared indicates that a server error occurred, but this shouldn't cause our deserialization to fail (though apparently, it is, because Gson isn't picking up our custom deserializer for `ClarifaiStatus` and is incorrectly trying to use the no-args constructor by default).

**Comment by hackable** [comment]
Every time we get this error.

**Comment by kevinmost** [comment]
@hackable, every time you get the JSON "internal server error" returned, or every time you get the exception about the constructor for ClarifaiStatus? Or both?

**Comment by hackable** [comment]
every time i get the exception about the constructor for ClarifaiStatus for sure.

**Comment by kevinmost** [comment]
@hackable We actually just had someone else face a similar issue, and it turns out that it was because they had conflicting versions of Gson in their project. We rely on Gson 2.7 or higher. Are you using an older version of Gson, or another dependency that might be bringing in an older version of Gson?

If you're using Maven, can you give me the output of `mvn dependency:tree`? 

And if you're using Gradle, the output of `./gradlew :moduleName:dependencies`, if you're using a Gradle submodule, or just `./gradlew :dependencies` if you're just using one root build.gradle script?

Thanks.

**Comment by akptan2** [comment]
Just update the gson in pom file

<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.8.0</version>
</dependency>

**Comment by KevCron** [comment]
@hackable Are you still getting this error?

**Comment by hackable** [comment]
no it was fixed when when we changed gson

**Comment by sankalp7654** [comment]
import java.util.List;
import java.io.IOException;
import clarifai2.api.ClarifaiBuilder;
import clarifai2.api.ClarifaiClient;
import clarifai2.dto.input.ClarifaiInput;
import clarifai2.dto.model.output.ClarifaiOutput;
import clarifai2.dto.prediction.Concept;

public class Main {
	public static void main(String [ ] args) throws IOException {
	
		ClarifaiClient client = new ClarifaiBuilder("b9d6962620224499b1762bad8e7f66de")
			    .buildSync();

	        final List<ClarifaiOutput<Concept>> predictionResults =
			    client.getDefaultModels().generalModel() 
			        .predict()
			        .withInputs(
			            ClarifaiInput.forImage("https://samples.clarifai.com/metro-north.jpg"))
			        .executeSync()
			        .get();
	
	}
}

**Comment by rok-povsic** [comment]
@sankalp7654 I'm not sure why you posted this piece of code but I've removed the API key and added code formatting.

**Comment by falhenaki** [comment]
I am having the same issue. Adding the com.google.code.gson dependency does not fix it.
